### ISSUE TITLE
Trace: unhandledRejection at: RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by MidSpike** [MidSpike/iris-utilities#42]
The issue occurs *randomly* **after** I.R.I.S. has played *~10 or more things* (using YouTube).

Once the issue has occurred, it will **always happen every time** something is played via YouTube.

```
----------------------------------------------------------------------------------------------------------------
Fri Nov 13 2020 12:24:10 GMT-0500
Trace: unhandledRejection at: RangeError: offset is out of bounds
    at Uint16Array.set (<anonymous>)
    at OpusScript.encode (C:\Users\tyler\node_modules\opusscript\index.js:51:16)
    at Encoder._encode (C:\Users\tyler\Desktop\iris-utilities\node_modules\prism-media\src\opus\Opus.js:60:25)
    at Encoder._transform (C:\Users\tyler\Desktop\iris-utilities\node_modules\prism-media\src\opus\Opus.js:143:30)
    at Encoder.Transform._read (_stream_transform.js:205:10)
    at Encoder.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Encoder.Writable.write (_stream_writable.js:303:10)
    at VolumeTransformer.ondata (_stream_readable.js:717:22)
    at VolumeTransformer.emit (events.js:314:20) Promise {
  <rejected> RangeError: offset is out of bounds
      at Uint16Array.set (<anonymous>)
      at OpusScript.encode (C:\Users\tyler\node_modules\opusscript\index.js:51:16)
      at Encoder._encode (C:\Users\tyler\Desktop\iris-utilities\node_modules\prism-media\src\opus\Opus.js:60:25)
      at Encoder._transform (C:\Users\tyler\Desktop\iris-utilities\node_modules\prism-media\src\opus\Opus.js:143:30)
      at Encoder.Transform._read (_stream_transform.js:205:10)
      at Encoder.Transform._write (_stream_transform.js:193:12)
      at writeOrBuffer (_stream_writable.js:352:12)
      at Encoder.Writable.write (_stream_writable.js:303:10)
      at VolumeTransformer.ondata (_stream_readable.js:717:22)
      at VolumeTransformer.emit (events.js:314:20)
}
    at process.<anonymous> (C:\Users\tyler\Desktop\iris-utilities\index.js:1157:13)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
----------------------------------------------------------------------------------------------------------------
```

**Comment by MidSpike** [comment]
The issue seems to have been solved after recent dependency updates.

However, I'm going to keep this issue open a bit longer.

**Comment by MidSpike** [comment]
I'm going to update this issue and mark it as resolved...

It seems that some dependency updates have fixed it.
